### ISSUE TITLE
Request for grade

### ISSUE THREAD

**Issue by hongnguyen11** [hongnguyen11/animal-rescue-website#1]
I would myself a B for this final assignment because I think I covered some of lessons I learned from this semester. 

@charlie-quinn

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
@hongnguyen11 ⚠️`Reminder: please close this issue since it has been resolved or expired.`
